name:  learn-github-action
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  push_job:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Display git diff
        run: |
          echo "showing git diff"
          git diff HEAD^ HEAD

  pull_request_job:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Display latest commit ID
        run: |
          echo "The latest commit ID is:"
          git rev-parse HEAD

